### ISSUE TITLE
Optimisation of PointTools using pandas

### ISSUE THREAD

**Issue by fclubb** [LSDtopotools/LSDMappingTools#12]
The LSDMap_PointTools object at the moment is set up in 2 different ways - one to read CSVs, and the other using pandas dataframes. We should all decide on one and then change the functions so that it all works together, rather than having a mix of both which is confusing. 
I vote for pandas as it's much more efficient... @bgailleton has already written some testing code to read in pandas dataframes as Point Tools (PANDEX!!), I think we should implement this as the standard way.
Any other opinions on this?

**Comment by bgailleton** [comment]
I vote for pandas as well, everything should be quicker! 
Everything should be adapted actually, Especially if you use the selectValue function that should cover all the masking operations for pandas dataframe.
What we can do if everyone is ok, I can switch on PANDEX on true by default but we can keep the old code during a time in case we discover some bugs?

**Comment by simon-m-mudd** [comment]
I agree. Everything should now be panda. Yes boris can you switch to PANDEX?

**Comment by bgailleton** [comment]
Cool ! I ll do it as soon as I have decent internet, on Wednesday probably.
Also I tested numpy for loading the raster I'll switch It on it optimize
the loading consequently.

Le 26 juin 2017 13:36, "Simon Marius Mudd" <notifications@github.com> a
écrit :

I agree. Everything should now be panda. Yes boris can you switch to PANDEX?

—
You are receiving this because you were assigned.

Reply to this email directly, view it on GitHub
<https://github.com/LSDtopotools/LSDMappingTools/issues/12#issuecomment-311034662>,
or mute the thread

**Comment by simon-m-mudd** [comment]
Hi Boris: The current fast raster loading is a bit buggy: it doesn't recognise nodata values. Can you test on some DEMs that have nodata? If you use the chi_mapping_tool you can mask out the low elevations by setting the minimum elevation

**Comment by bgailleton** [comment]
Hi Simon,
I can sort this bug tomorrow, the nodata value is stored in the HDR file
right?

Le 26 juin 2017 19:06, "Simon Marius Mudd" <notifications@github.com> a
écrit :

**Comment by simon-m-mudd** [comment]
Yes, but sometimes it is missing! If it can't be found it should default to -9999

**Comment by simon-m-mudd** [comment]
As far as I can tell this is now fixed.
